# 网关配置
gateway:
    # 监听端口
    port: 8080
    # 本地缓存过期时间(分钟)
    local-cache-expire: 10
    # Redis缓存过期时间(分钟)
    redis-cache-expire: 60
    # 数据路径
    data-path: "data"
    # 临时路径
    temp-path: "tmp"

# 认证配置
auth:
    # 加密密钥
    master-key: "b8757330c18fe65a8ce7b0733355e292"
    # 时间戳窗口(秒)
    timestamp-window: 5
    # nonce 唯一性校验窗口(次)
    nonce-window: 2
    # nonce 唯一性校验窗口(小时)
    nonce-window-hour: 24
    # 每秒最大请求数
    qps-limit: 3
    # 每分钟最大请求数
    qpm-limit: 100
    # 全局IP黑名单
    ip-black-list:
#        - "127.0.0.1"
    # 全局国家黑名单
    country-black-list:
#        - "EN"

# 日志配置
logger:
    # 日志输出方式
    output: "stdout"
    # 系统日志文件路径
    log-path: "logs/api-gateway.log"
    # 请求日志文件路径
    request-log-path: "logs/request.log"
    # 日志文件最大大小(MB)
    max-size: 100
    # 日志文件最大备份数量
    max-backups: 10
    # 日志文件最大年龄(天)
    max-age: 30
    # 是否压缩日志文件
    compress: true


health:
    # 数据库健康检查间隔(秒)
    db-health-check-interval: 10
    # 数据库健康检查失败阈值
    db-health-check-fail-threshold: 3
    # 数据库健康检查成功阈值
    db-health-check-ok-threshold: 1
    # Redis健康检查间隔(秒)
    redis-health-check-interval: 10
    # Redis健康检查失败阈值
    redis-health-check-fail-threshold: 3
    # Redis健康检查成功阈值
    redis-health-check-ok-threshold: 1
    # IP数据库健康检查间隔(秒)
    ipdb-health-check-interval: 20
    # IP数据库健康检查失败阈值
    ipdb-health-check-fail-threshold: 3
    # IP数据库健康检查成功阈值
    ipdb-health-check-ok-threshold: 1

# 数据库配置
db:
    # 主机地址
    host: "localhost"
    # 端口
    port: 3306
    # 用户名
    user: "elake_api_gateway"
    # 密码
    password: "JktUjAoFCLmeDAw2"
    # 库名
    name: "elake_api_gateway"
    # 最大连接数
    max-open-connections: 50
    # 最大空闲连接数
    max-idle-connections: 10
    # 单连接最大存活时间(秒)
    conn-max-lifetime: 3600
    # 空闲最大时间(秒)
    conn-max-idle-time: 300
    # 读取超时时间(秒)
    read-timeout: 5
    # 写入超时时间(秒)
    write-timeout: 5

# Redis配置
redis:
    # 主机地址
    host: "localhost"
    # 端口
    port: 6379
    # 密码
    password: ""
    # 库索引
    db: 0
    # 项目前缀
    project-prefix: "elake-api"
    # 连接池大小
    pool-size: 100
    # 最小空闲连接数
    min-idle-connections: 10
    # 连接最大空闲时间(分钟)
    connection-max-idle-time: 15
    # 连接超时时间(秒)
    dial-timeout: 5
    # 读取超时时间(秒)
    read-timeout: 5
    # 写入超时时间(秒)
    write-timeout: 5

# IPDB
ipdb:
    # IPDB 令牌
    token: "iWWtrT3GBgOpraaSA0q8nWL3TFhiE2FtsUdEKANE3wX40WW7dK4Mpt5t172nF7Me"
    # 最大下载尝试次数
    max-download-attempts: 5
